language: python
python:
  - "2.6"
  - "2.7"
  # - "3.3"
  - "pypy"
install:
  # - pip install --use-mirrors -r requirements.txt
  - python setup.py install
  - python setup_validate.py install
script: nosetests
